"""Inject the atlas motion system into about.html and method.html.

Ports the shared whole-page instruments — the ether (star-dust + meteors),
staggered block reveals with engraving-wipe headings, the fixed top bar, the
meridian section rail, and the brass reticle — into both companion pages.
Idempotent: everything lives between PAGE-MOTION markers.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
V = PROJECT_ROOT / "data/analysis/iclr/unit-taxonomy-2026-v1"
BEGIN = "<!-- PAGE-MOTION BEGIN (generated by scripts/add_page_motion.py) -->"
END = "<!-- PAGE-MOTION END -->"

ATLAS_URL = "https://claude.ai/code/artifact/0aa65ded-3852-4a3c-8994-0db2fe393e09"
ABOUT_URL = "https://claude.ai/code/artifact/6f0ed75c-f899-47ce-870e-6c3d5c45cc48"
METHOD_URL = "https://claude.ai/code/artifact/c76a5355-ce79-456e-9193-d1be6a6a0baa"


def block(page: str) -> str:
    here = {"about": "About", "method": "Method"}[page]
    links = [
        ("About", ABOUT_URL), ("Method", METHOD_URL), ("The Atlas", ATLAS_URL),
        ("GitHub", "https://github.com/t46/atlas-of-judgment"),
        ("Data", "https://huggingface.co/datasets/t46/atlas-of-judgment"),
        ("Live", "https://atlas-of-judgment.pages.dev"),
    ]
    nav = "".join(
        f'<a href="{"#top" if n == here else u}"{" class=\"tb-here\"" if n == here else (" class=\"tb-live\"" if n == "Live" else "")}>{n}</a>'
        for n, u in links
    )
    return f'''{BEGIN}
<style>
#ether {{ position: fixed; inset: 0; width: 100vw; height: 100vh; z-index: -1; pointer-events: none; }}
.mv {{ opacity: 0; transform: translateY(14px); transition: opacity 0.7s ease, transform 0.7s ease; }}
.mv.in {{ opacity: 1; transform: none; }}
h2.mv {{ clip-path: inset(-6% 100% -10% 0); transition: opacity 0.5s ease, transform 0.7s ease, clip-path 1.1s cubic-bezier(0.3, 0.6, 0.2, 1) 0.1s; }}
h2.mv.in {{ clip-path: inset(-6% -2% -10% 0); }}
#topbar {{ position: fixed; top: 0; left: 0; right: 0; z-index: 70; display: flex; align-items: center; justify-content: space-between; gap: 14px; padding: 9px clamp(14px, 3vw, 40px); background: rgba(18,16,31,0.82); backdrop-filter: blur(10px); border-bottom: 1px solid var(--brass-faint); transform: translateY(-100%); transition: transform 0.4s cubic-bezier(0.2, 0.7, 0.15, 1); }}
#topbar.show {{ transform: translateY(0); }}
#topbar .tb-mark {{ font-family: var(--mono); font-size: 10px; letter-spacing: 0.3em; text-transform: uppercase; color: var(--brass); text-decoration: none; border: none; white-space: nowrap; }}
#topbar .tb-links {{ display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 4px clamp(10px, 2.4vw, 26px); }}
#topbar .tb-links a {{ font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--ink-2); text-decoration: none; border: none; white-space: nowrap; }}
#topbar .tb-links a:hover {{ color: var(--brass); }}
#topbar .tb-links a.tb-live, #topbar .tb-links a.tb-here {{ color: var(--brass); }}
@media (max-width: 560px) {{ #topbar .tb-mark {{ letter-spacing: 0.14em; }} #topbar .tb-links {{ gap: 9px; }} #topbar .tb-links a {{ font-size: 8px; letter-spacing: 0.08em; }} }}
#meridian {{ position: fixed; right: 16px; top: 50%; transform: translateY(-50%); z-index: 50; display: flex; flex-direction: column; align-items: flex-end; gap: 7px; }}
#meridian .m-track {{ position: absolute; right: 6px; top: -14px; bottom: -14px; width: 1px; background: rgba(201,164,92,0.14); }}
#meridian .m-fill {{ position: absolute; right: 6px; top: -14px; width: 1px; background: var(--brass); }}
#meridian button {{ position: relative; display: block; width: 13px; height: 2px; padding: 0; background: rgba(201,164,92,0.35); border: none; cursor: pointer; transition: width 0.25s ease, background 0.25s ease; }}
#meridian button:hover, #meridian button.cur {{ width: 22px; background: var(--brass); }}
#meridian button .m-lab {{ position: absolute; right: 30px; top: 50%; transform: translateY(-50%); font-family: var(--mono); font-size: 8.5px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--brass); white-space: nowrap; opacity: 0; transition: opacity 0.25s ease; pointer-events: none; background: rgba(18,16,31,0.9); padding: 3px 7px; border: 1px solid var(--brass-faint); }}
#meridian button:hover .m-lab, #meridian button.cur .m-lab {{ opacity: 1; }}
#meridian button.cur .m-lab {{ color: var(--ink-2); border-color: transparent; background: none; }}
#meridian .m-pct {{ font-family: var(--mono); font-size: 7.5px; letter-spacing: 0.14em; color: var(--muted); margin-top: 6px; }}
@media (max-width: 1180px) {{ #meridian {{ display: none; }} }}
#reticle {{ position: fixed; left: 0; top: 0; width: 26px; height: 26px; margin: -13px 0 0 -13px; pointer-events: none; z-index: 200; opacity: 0; transition: opacity 0.3s ease; }}
#reticle::before {{ content: ""; position: absolute; inset: 0; border: 1px solid rgba(201,164,92,0.55); border-radius: 50%; transition: transform 0.3s cubic-bezier(0.3, 0.6, 0.2, 1), border-color 0.3s ease; }}
#reticle::after {{ content: ""; position: absolute; left: 50%; top: 50%; width: 2px; height: 2px; margin: -1px 0 0 -1px; background: var(--brass); border-radius: 50%; }}
#reticle.hot::before {{ transform: scale(1.7); border-color: var(--brass); }}
.fm-box {{ opacity: 0; transform: translateY(10px); transition: opacity 0.6s ease, transform 0.6s ease; }}
.diagram.in .fm-box {{ opacity: 1; transform: none; }}
.fun-bar {{ transform-origin: left center; transform: scaleX(0); transition: transform 0.9s cubic-bezier(0.2, 0.7, 0.15, 1); }}
.diagram.in .fun-bar {{ transform: scaleX(1); }}
.hm .cell {{ opacity: 0; transition: opacity 0.45s ease; }}
.hm.in .cell {{ opacity: 1; }}
@media (prefers-reduced-motion: reduce) {{
  .mv, h2.mv, .fm-box, .fun-bar, .hm .cell {{ opacity: 1 !important; transform: none !important; transition: none !important; clip-path: none !important; }}
  #topbar, #reticle {{ transition: none; }}
}}
</style>
<canvas id="ether" aria-hidden="true"></canvas>
<nav id="topbar" aria-label="site"><a class="tb-mark" href="#top">Atlas of Judgment</a><div class="tb-links">{nav}</div></nav>
<nav id="meridian" aria-label="sections"><div class="m-track"></div><div class="m-fill" id="m-fill"></div></nav>
<div id="reticle" aria-hidden="true"></div>
<script>
(function pageMotion() {{
  const REDUCED = matchMedia("(prefers-reduced-motion: reduce)").matches;
  // ---- ether ----
  if (!REDUCED) {{
    const cv = document.getElementById("ether");
    const ctx = cv.getContext("2d");
    let W = 0, H = 0, motes = [], meteor = null, nextMeteor = performance.now() + 9000 + Math.random() * 14000;
    function size() {{
      W = innerWidth; H = innerHeight;
      const dpr = Math.min(devicePixelRatio || 1, 1.5);
      cv.width = W * dpr; cv.height = H * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      const N = Math.min(150, Math.round(W * H / 9000));
      motes = [];
      for (let i = 0; i < N; i++) motes.push({{ x: Math.random() * W, y: Math.random() * H,
        vy: -(0.03 + Math.random() * 0.09), ph: Math.random() * 6.283,
        sz: 0.7 + Math.random() * 1.2, brass: Math.random() < 0.2, a: 0.07 + Math.random() * 0.13 }});
    }}
    let last = performance.now();
    (function tick(now) {{
      requestAnimationFrame(tick);
      if (document.hidden) {{ last = now; return; }}
      const dt = Math.min(now - last, 50) / 16.7; last = now;
      ctx.clearRect(0, 0, W, H);
      for (const m of motes) {{
        m.y += m.vy * dt; m.x += Math.sin(now / 4200 + m.ph) * 0.05 * dt;
        if (m.y < -4) {{ m.y = H + 4; m.x = Math.random() * W; }}
        const a = m.a * (0.7 + 0.3 * Math.sin(now / 1500 + m.ph));
        ctx.fillStyle = m.brass ? `rgba(201,164,92,${{a.toFixed(3)}})` : `rgba(220,225,240,${{a.toFixed(3)}})`;
        ctx.fillRect(m.x, m.y, m.sz, m.sz);
      }}
      if (!meteor && now > nextMeteor) {{
        const L = Math.random() < 0.5;
        meteor = {{ x0: L ? -60 : W + 60, y0: Math.random() * H * 0.55, dx: (L ? 1 : -1) * (0.55 + Math.random() * 0.3), dy: 0.22 + Math.random() * 0.18, born: now }};
        nextMeteor = now + 16000 + Math.random() * 22000;
      }}
      if (meteor) {{
        const age = now - meteor.born;
        if (age > 900) meteor = null;
        else {{
          const x = meteor.x0 + meteor.dx * age, y = meteor.y0 + meteor.dy * age, fade = Math.sin(age / 900 * Math.PI);
          const g = ctx.createLinearGradient(x - meteor.dx * 90, y - meteor.dy * 90, x, y);
          g.addColorStop(0, "rgba(201,164,92,0)");
          g.addColorStop(1, `rgba(236,231,220,${{(0.35 * fade).toFixed(3)}})`);
          ctx.strokeStyle = g; ctx.lineWidth = 1;
          ctx.beginPath(); ctx.moveTo(x - meteor.dx * 90, y - meteor.dy * 90); ctx.lineTo(x, y); ctx.stroke();
        }}
      }}
    }})(last);
    size(); addEventListener("resize", size);
  }} else {{ document.getElementById("ether").remove(); }}
  // ---- block reveals ----
  const shell = document.querySelector(".shell");
  const blocks = [...shell.children].filter(el => !/^(NAV|SCRIPT|STYLE)$/.test(el.tagName));
  const io = new IntersectionObserver(en => {{
    for (const e of en) if (e.isIntersecting) {{ e.target.classList.add("in"); io.unobserve(e.target); }}
  }}, {{ threshold: 0.08 }});
  for (const el of blocks) {{ el.classList.add("mv"); io.observe(el); }}
  for (const el of document.querySelectorAll(".diagram, .hm")) io.observe(el);
  document.querySelectorAll(".hm").forEach(hm => {{
    [...hm.querySelectorAll(".cell")].forEach((c, i) => c.style.transitionDelay = Math.min(i * 4, 800) + "ms");
  }});
  document.querySelectorAll(".diagram .fm-box").forEach((b, i) => b.style.transitionDelay = (i * 90) + "ms");
  // ---- top bar + meridian ----
  const topbar = document.getElementById("topbar");
  const rail = document.getElementById("meridian");
  const fill = document.getElementById("m-fill");
  const marks = [...document.querySelectorAll(".no")].map(no => {{
    let h = no.nextElementSibling;
    while (h && !/^H[23]$/.test(h.tagName)) h = h.nextElementSibling;
    return {{ el: no, lab: h ? h.textContent.trim().slice(0, 26) : no.textContent.trim() }};
  }});
  const pct = document.createElement("div"); pct.className = "m-pct"; pct.textContent = "000%";
  const entries = [{{ el: shell, lab: "Top" }}].concat(marks);
  for (const en of entries) {{
    const b = document.createElement("button");
    b.innerHTML = `<span class="m-lab">${{en.lab}}</span>`;
    b.addEventListener("click", () => en.el.scrollIntoView({{ behavior: REDUCED ? "auto" : "smooth", block: "start" }}));
    rail.appendChild(b); en.btn = b;
  }}
  rail.appendChild(pct);
  let cur = -1;
  function onScroll() {{
    const dh = document.documentElement.scrollHeight - innerHeight;
    const p = dh ? scrollY / dh : 0;
    fill.style.height = (p * 100).toFixed(2) + "%";
    pct.textContent = String(Math.round(p * 100)).padStart(3, "0") + "%";
    topbar.classList.toggle("show", scrollY > 420);
    let best = 0;
    entries.forEach((en, i) => {{ if (en.el.getBoundingClientRect().top <= innerHeight * 0.4) best = i; }});
    if (best !== cur) {{ cur = best; entries.forEach((en, i) => en.btn.classList.toggle("cur", i === best)); }}
  }}
  addEventListener("scroll", onScroll, {{ passive: true }});
  onScroll();
  // ---- reticle ----
  if (!REDUCED && matchMedia("(pointer: fine)").matches) {{
    const ret = document.getElementById("reticle");
    let mx = -100, my = -100, rx = -100, ry = -100, seen = false;
    addEventListener("mousemove", e => {{
      mx = e.clientX; my = e.clientY;
      if (!seen) {{ seen = true; ret.style.opacity = 1; rx = mx; ry = my; }}
      const el = e.target instanceof Element ? e.target : null;
      ret.classList.toggle("hot", !!(el && el.closest("a, button, summary, select, code, .fbar")));
    }}, {{ passive: true }});
    document.documentElement.addEventListener("mouseleave", () => {{ ret.style.opacity = 0; seen = false; }});
    (function loop() {{
      requestAnimationFrame(loop);
      rx += (mx - rx) * 0.22; ry += (my - ry) * 0.22;
      ret.style.transform = `translate(${{rx.toFixed(1)}}px, ${{ry.toFixed(1)}}px)`;
    }})();
  }} else {{ document.getElementById("reticle").remove(); }}
}})();
</script>
{END}'''


def inject(path: Path, page: str) -> None:
    s = path.read_text()
    b = block(page)
    if BEGIN in s and END in s:
        s = s[: s.index(BEGIN)] + b + s[s.index(END) + len(END):]
    else:
        s = s.rstrip() + "\n\n" + b + "\n"
    if 'id="top"' not in s:
        s = s.replace('<div class="shell">', '<div class="shell" id="top">', 1)
    path.write_text(s)
    print(f"{path.name}: motion injected ({len(b)/1e3:.1f} KB)")


def main() -> None:
    inject(V / "about.html", "about")
    inject(V / "method.html", "method")


if __name__ == "__main__":
    main()
