"""Inject the instrument-check figures and the raw-specimen explorer into method.html.

These two blocks document the reading instrument itself (support_status
reliability; construct validity against ICLR sub-scores) and expose the 232
sampled reviews as inspectable structured logic flows. They live on the Method
page rather than the atlas: they are statements about the instrument, not
findings about reviewers.

Idempotent: content is written between METHOD-EXTRAS markers; rerun after any
upstream data rebuild. Sources: viz-data.json (labels, order, samples),
panel-data.json (reliability grid), construct-data.json.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
V = PROJECT_ROOT / "data/analysis/iclr/unit-taxonomy-2026-v1"
D = PROJECT_ROOT / "data/analysis/iclr/unit-taxonomy-direct-v1"
METHOD = V / "method.html"
BEGIN = "<!-- METHOD-EXTRAS BEGIN (generated by scripts/build_method_extras.py) -->"
END = "<!-- METHOD-EXTRAS END -->"


def main() -> None:
    viz = json.loads((V / "viz-data.json").read_text())
    panel = json.loads((D / "panel-data.json").read_text())
    construct = json.loads((V / "construct-data.json").read_text())

    obj_label = {c["key"]: c["label_en"] for c in viz["taxonomy"]["inspected_object"]}
    rea_label = {c["key"]: c["label_en"] for c in viz["taxonomy"]["reasoning"]}
    obj_tot: dict[str, int] = defaultdict(int)
    rea_tot: dict[str, int] = defaultdict(int)
    for t in viz["triples"]:
        obj_tot[t["o"]] += t["n"]
        rea_tot[t["r"]] += t["n"]
    obj_order = sorted(obj_tot, key=lambda k: -obj_tot[k])
    rea_order = sorted(rea_tot, key=lambda k: -rea_tot[k])

    payload = {
        "objLabel": obj_label, "reaLabel": rea_label,
        "objOrder": obj_order, "reaOrder": rea_order,
        "rel": panel["reliability"],
        "construct": construct["matrix"],
            }
    data_js = json.dumps(payload).replace("</", "<\\/")

    css = """
<style>
.hm-wrap { }
.hm { display: grid; gap: 2px; }
.hm .rl { font-size: 12.5px; color: var(--ink-2); display: flex; align-items: center; justify-content: flex-end; padding-right: 12px; }
.hm .cl { font-family: var(--mono); font-size: 11px; color: var(--ink-2); justify-self: center; align-self: center; padding: 4px 0; }
.hm .cell { height: 26px; }
.hm .cell:hover { outline: 1px solid var(--brass); outline-offset: -1px; }
.fig-cap { font-family: var(--mono); font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--brass); margin: 26px 0 12px; }
.hm-note { font-size: 13px; color: var(--ink-2); margin-top: 12px; }
@media (max-width: 700px) { .hm .rl { font-size: 8.5px; white-space: normal; line-height: 1.15; padding-right: 6px; } .hm .cell { height: 20px; } }
.unit-toggle { font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.16em; text-transform: uppercase; background: none; border: 1px dashed var(--brass-line); color: var(--brass); padding: 6px 14px; cursor: pointer; margin-top: 10px; align-self: flex-start; transition: background .25s ease; }
.unit-toggle:hover { border-style: solid; background: rgba(201,164,92,0.08); }
.unit-toggle .arr { display: inline-block; transition: transform .45s cubic-bezier(.25,.8,.25,1); margin-left: 6px; }
.unit-toggle.open .arr { transform: rotate(180deg); }
.unit-fold { display: grid; grid-template-rows: 0fr; transition: grid-template-rows .6s cubic-bezier(.25,.8,.25,1); }
.unit-fold.open { grid-template-rows: 1fr; }
.unit-fold > .uf-inner { min-height: 0; overflow: hidden; }
@keyframes specIn { from { opacity: 0; transform: translateY(14px); } to { opacity: 1; transform: none; } }
.spec-in { animation: specIn .45s cubic-bezier(.2,.7,.2,1) both; }
#sp-more, #sp-less { background: none; color: var(--brass); border: 1px solid var(--brass-line); padding: 10px 32px; font-family: var(--mono); font-size: 10.5px; letter-spacing: 0.2em; text-transform: uppercase; cursor: pointer; }
#sp-more:hover, #sp-less:hover { background: rgba(201,164,92,0.08); }
@media (prefers-reduced-motion: reduce) { .unit-fold, .unit-toggle .arr { transition: none !important; } .spec-in { animation: none !important; } }
</style>"""

    html = f"""{BEGIN}
{css}

<div class="no" id="s7">07</div>
<h2>Instrument checks — reading the reader</h2>
<p>Everything above describes how the data was made; this section asks how far the machine reading can be trusted. Two checks, both computed from the shipped unit databases. They are also shown in the atlas, but they belong here: they are statements about the instrument, not findings about reviewers.</p>

<h3>Support status — where the instrument speaks with its own voice</h3>
<p>Every unit carries a <code>support_status</code> field assigned at structuring time: <b>reviewer_explicit</b> (grounded in the reviewer's stated words), <b>memo_inferred</b> (articulated by the DeepSeek memo from context rather than quoted), or <b>mixed</b>. The two tracks differ sharply by construction — the review-level 2026 track runs 19.8% explicit / 77.1% inferred / 3.1% mixed, while the forum-level track runs 57.4% / 40.8% / 1.7% — because the Layered prompts ask the memo to synthesize, and the Direct prompts demand line-ID citations. The share is not uniform across categories or years:</p>
<div class="fig-cap">Memo-inferred share, object × year — forum-level track (deeper violet = more inferred)</div>
<div class="hm-wrap"><div class="hm" id="mx-rel"></div></div>
<p class="hm-note">Categories and years where the violet deepens are where downstream figures speak more with the instrument's voice than the reviewer's. Rebuild: <code>uv run python scripts/build_panel_data.py</code> → <code>panel-data.json</code> (key <code>reliability</code>).</p>

<h3>Construct validity — do the induced categories track the venue's own decomposition?</h3>
<p>The taxonomy was induced from embeddings, not designed, so it needs an external criterion. ICLR asks reviewers for three sub-scores (soundness · presentation · contribution, 1–4; the fields exist only since 2024). For each object of scrutiny we compare mean sub-scores of reviews that carry at least one negative unit on that object against reviews at the <em>same overall rating</em> without one, weight the per-rating deltas by prevalence (cells with fewer than 30 reviews on either side are dropped), and read whether each criticism dents the sub-score it should. Computed over all 74,380 rated 2026 reviews.</p>
<div class="fig-cap">Rating-adjusted Δ sub-score when a negative unit is present (oxblood = drops, verdigris = rises)</div>
<div class="hm-wrap"><div class="hm" id="mx-con"></div></div>
<p class="hm-note">The grid largely agrees with the venue's own decomposition — clarity criticism dents <em>presentation</em> specifically (−0.35), novelty dents <em>contribution</em> (−0.12) — with one telling leak: theory criticism dents presentation more than soundness, as if "I could not follow the theory" were filed under presentation. Rebuild: <code>uv run python scripts/build_construct_data.py</code> → <code>construct-data.json</code>.</p>

<h3 id="ruler">The moving ruler — nine years of the rating scale</h3>
<p>The venue's own instrument did not hold still. Enumerating every rating string in the record (all 199,031 official reviews) gives four distinct scoring forms, and any figure that compares scores across years has to reckon with them:</p>
<div class="tw"><table>
  <tr><th>Years</th><th>Field</th><th>Levels observed</th><th>Anchors</th></tr>
  <tr><td>2018–19, 2021</td><td><code>rating</code></td><td>ten: 1–10</td><td>labeled; 5 = "marginally below the acceptance threshold", 6 = "marginally above"</td></tr>
  <tr><td>2020</td><td><code>rating</code></td><td>four: 1, 3, 6, 8</td><td>Reject / Weak Reject / Weak Accept / Accept; the only year with no confidence score (an "experience assessment" instead)</td></tr>
  <tr><td>2022–25</td><td><code>recommendation</code> ('22–23), then <code>rating</code></td><td>six: 1, 3, 5, 6, 8, 10</td><td>labeled through 2024 (same threshold anchors at 5/6); bare integers in the 2025 record</td></tr>
  <tr><td>2026</td><td><code>rating</code></td><td>six: 0, 2, 4, 6, 8, 10</td><td>bare even integers; no shared threshold anchor with earlier years</td></tr>
</table></div>
<h3 id="elements-audit">The elements audit — three blind readers</h3>
<p>Plate X decomposes "not novel" into elements by clustering (data-driven terrain) and analyst merging (hand-drawn borders). To audit the borders, three independent machine readers (Claude Haiku agents) were each given 60 raw novelty denials and <em>no taxonomy</em>, and asked what each denial actually says. All three independently re-derived the plate's main families — the obvious combination, the insufficient increment, undifferentiated prior art, anticipation, restating the known, mere transfer, the discounted non-method contribution, and the venue-indexed bar — and one reader independently reproduced the decision to keep the <em>imported evidence rule</em> as its own element. Two elements the clustering had folded away surfaced in the audit and are recorded here as finer clauses: the <b>false-priority accusation</b> (the paper claims to be first, and the reviewer says the claim is untrue — an accusation of attribution, not of similarity; ≈3–7% of audited samples, folded inside "restating the known"), and the <b>unlocated contribution</b> (the reviewer cannot find what the paper claims is new; ≈5–10%, all three readers surfaced it). The second is best read the way the imported evidence rule is read: the charge is filed in novelty's docket but the operative law is presentation's — with one substantive twist that keeps it from being a mere clarity issue: reviewers treat novelty that cannot be located as novelty that does not exist, which is to say the venue's operative novelty is a property of the artifact <em>plus its argument</em>, never the artifact alone — consistent with the differentiation rule's burden-of-articulation clause, and with the fact that the dominant remedy for novelty is work of writing. Audit protocol and transcripts ship with the repository.</p>

<p>How the atlas handles this: score distributions are always drawn per year on that year's own levels (Figs. 11d, 11e) and the scale changes are named in the captions; the score-spread claim (Fig. 10c) uses entropy normalized to each year's own level count, so a change of form cannot masquerade as a change of behavior; the intraclass correlation (Fig. 10a) is a variance ratio and so survives relabeling, but coarser grids mechanically deflate it — the 2026 point is dashed and flagged for exactly this reason. Raw-point quantities (means, reviewer-pair gaps) are never compared across form boundaries. Sub-scores (soundness · presentation · contribution) exist only from 2024, which is why the construct-validity check above is confined to recent years.</p>

<script>
const MX = {data_js};
(function () {{
  const fmt = n => n.toLocaleString("en-US");
  const pct = x => (100 * x).toFixed(1) + "%";
  const objLabel = MX.objLabel, reaLabel = MX.reaLabel, objOrder = MX.objOrder, reaOrder = MX.reaOrder;

  // ---- reliability heatmap ----
  const R = MX.rel;
  const rel = document.getElementById("mx-rel");
  rel.style.gridTemplateColumns = `minmax(86px, 210px) repeat(${{R.years.length}}, 1fr)`;
  rel.insertAdjacentHTML("beforeend", `<div></div>` + R.years.map(y => `<div class="cl">'${{String(y).slice(2)}}</div>`).join(""));
  for (const o of objOrder) {{
    const vals = R.memo_inferred_share[o]; if (!vals) continue;
    rel.insertAdjacentHTML("beforeend", `<div class="rl">${{objLabel[o]}}</div>`);
    vals.forEach((v, i) => {{
      const cell = document.createElement("div");
      cell.className = "cell";
      cell.style.background = `color-mix(in oklab, #6b5d94 ${{Math.min(92, Math.round(4 + v * 96))}}%, #f3ead2)`;
      cell.title = `${{objLabel[o]}} · ${{R.years[i]}}: ${{pct(v)}} memo-inferred`;
      rel.appendChild(cell);
    }});
  }}

  // ---- construct-validity heatmap ----
  const SUBS = ["soundness", "presentation", "contribution"];
  const con = document.getElementById("mx-con");
  con.style.gridTemplateColumns = `minmax(86px, 210px) repeat(${{SUBS.length}}, 1fr)`;
  con.insertAdjacentHTML("beforeend", `<div></div>` + SUBS.map(x => `<div class="cl">${{x}}</div>`).join(""));
  for (const o of objOrder) {{
    con.insertAdjacentHTML("beforeend", `<div class="rl">${{objLabel[o]}}</div>`);
    for (const sub of SUBS) {{
      const v = (MX.construct[o] || {{}})[sub] || 0;
      const mag = Math.min(92, Math.round(6 + Math.abs(v) / 0.35 * 86));
      const cell = document.createElement("div");
      cell.className = "cell";
      cell.style.background = `color-mix(in oklab, ${{v < 0 ? "#6f1f45" : "#356b43"}} ${{mag}}%, #f3ead2)`;
      cell.title = `negative ${{objLabel[o]}} unit × ${{sub}}: Δ mean = ${{v > 0 ? "+" : ""}}${{v.toFixed(3)}} (rating-adjusted)`;
      con.appendChild(cell);
    }}
  }}

}})();
</script>
{END}
"""
    # the ▾ escape must survive into JS source
    html = html.replace("\\\\u25be", "\\u25be")

    s = METHOD.read_text()
    if BEGIN in s and END in s:
        # The replace below is wholesale: anything sitting inside the markers is destroyed.
        # Hand-written sections have drifted in here before (the provenance ledger among
        # them), so refuse rather than silently delete work this script cannot regenerate.
        import re as _re
        cur = s[s.index(BEGIN) : s.index(END)]
        orphans = [i for i in _re.findall(r'<h[23][^>]*\bid="([^"]+)"', cur)
                   if f'id="{i}"' not in html]
        if orphans:
            raise SystemExit(
                "refusing to overwrite METHOD-EXTRAS: the block contains section(s) this "
                "script does not generate and would delete: " + ", ".join(orphans) +
                ". Move them below the METHOD-EXTRAS END marker first."
            )
        s = s[: s.index(BEGIN)] + html + s[s.index(END) + len(END) + 1 :]
    else:
        assert "<footer>" in s
        s = s.replace("<footer>", html + "\n<footer>", 1)

    # TOC entries
    # The page's contents are hand-maintained since the four-part restructure of
    # 2026-08-26; this block is section 07 there. Assert rather than re-insert, so a
    # future renumbering that forgets this file fails loudly instead of drifting.
    assert '<a href="#s7">' in s, "method.html has no #s7 entry — the contents and this generator disagree"
    # footer scope line
    s = s.replace("<span>Scope: data creation only</span>", "<span>Scope: data creation &amp; instrument validation</span>", 1)

    METHOD.write_text(s)
    print(f"method extras injected ({len(html) / 1e6:.2f} MB block); method.html now {len(s) / 1e6:.2f} MB")


if __name__ == "__main__":
    main()
