"""Inject the instrument-check figures and the raw-specimen explorer into method.html.

These two blocks document the reading instrument itself (support_status
reliability; construct validity against ICLR sub-scores) and expose the 232
sampled reviews as inspectable structured logic flows. They live on the Method
page rather than the atlas: they are statements about the instrument, not
findings about reviewers.

Idempotent: content is written between METHOD-EXTRAS markers; rerun after any
upstream data rebuild. Sources: viz-data.json (labels, order, samples),
panel-data.json (reliability grid), construct-data.json.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
V = PROJECT_ROOT / "data/analysis/iclr/unit-taxonomy-2026-v1"
D = PROJECT_ROOT / "data/analysis/iclr/unit-taxonomy-direct-v1"
METHOD = V / "method.html"
BEGIN = "<!-- METHOD-EXTRAS BEGIN (generated by scripts/build_method_extras.py) -->"
END = "<!-- METHOD-EXTRAS END -->"


def main() -> None:
    viz = json.loads((V / "viz-data.json").read_text())
    panel = json.loads((D / "panel-data.json").read_text())
    construct = json.loads((V / "construct-data.json").read_text())

    obj_label = {c["key"]: c["label_en"] for c in viz["taxonomy"]["inspected_object"]}
    rea_label = {c["key"]: c["label_en"] for c in viz["taxonomy"]["reasoning"]}
    obj_tot: dict[str, int] = defaultdict(int)
    rea_tot: dict[str, int] = defaultdict(int)
    for t in viz["triples"]:
        obj_tot[t["o"]] += t["n"]
        rea_tot[t["r"]] += t["n"]
    obj_order = sorted(obj_tot, key=lambda k: -obj_tot[k])
    rea_order = sorted(rea_tot, key=lambda k: -rea_tot[k])

    payload = {
        "objLabel": obj_label, "reaLabel": rea_label,
        "objOrder": obj_order, "reaOrder": rea_order,
        "rel": panel["reliability"],
        "construct": construct["matrix"],
            }
    data_js = json.dumps(payload).replace("</", "<\\/")

    css = """
<style>
.hm-wrap { }
.hm { display: grid; gap: 2px; }
.hm .rl { font-size: 12.5px; color: var(--ink-2); display: flex; align-items: center; justify-content: flex-end; padding-right: 12px; }
.hm .cl { font-family: var(--mono); font-size: 11px; color: var(--ink-2); justify-self: center; align-self: center; padding: 4px 0; }
.hm .cell { height: 26px; }
.hm .cell:hover { outline: 1px solid var(--brass); outline-offset: -1px; }
.fig-cap { font-family: var(--mono); font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--brass); margin: 26px 0 12px; }
.hm-note { font-size: 13px; color: var(--ink-2); margin-top: 12px; }
@media (max-width: 700px) { .hm .rl { font-size: 8.5px; white-space: normal; line-height: 1.15; padding-right: 6px; } .hm .cell { height: 20px; } }
.filters { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin: 18px 0; }
.filters select { background: var(--raise); color: var(--ink); border: 1px solid var(--brass-line); padding: 8px 12px; font-size: 11.5px; font-family: var(--mono); }
.filters .count { margin-left: auto; font-family: var(--mono); font-size: 10.5px; color: var(--muted); letter-spacing: 0.1em; }
.review-card { border: 1px solid var(--brass-faint); background: rgba(22,19,36,0.5); padding: 22px 22px; display: flex; flex-direction: column; gap: 14px; }
.review-head { display: flex; flex-wrap: wrap; gap: 8px 14px; align-items: baseline; border-bottom: 1px solid var(--brass-faint); padding-bottom: 12px; }
.review-head .title { font-family: var(--display); font-size: 19px; font-weight: 600; border: none; color: var(--ink); }
.review-head a.title:hover, .review-head a.rid:hover { color: var(--brass); }
.review-head .rid { font-family: var(--mono); font-size: 10px; color: var(--muted); letter-spacing: 0.08em; border: none; }
.chip { display: inline-block; font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.1em; padding: 2px 9px; border: 1px solid var(--brass-faint); color: var(--ink-2); white-space: nowrap; }
.chip.acc { border-color: #199e70; color: #199e70; }
.chip.rej { border-color: #e66767; color: #e66767; }
.summary { color: var(--ink-2); font-style: italic; font-size: 14px; }
.unit { display: grid; grid-template-columns: 3px 1fr; background: rgba(26,23,41,0.75); border: 1px solid var(--brass-faint); margin-top: 10px; }
.unit .stripe { height: 100%; }
.unit .flow { display: grid; grid-template-columns: repeat(4, 1fr); padding: 12px 14px 14px 0; }
.unit .step { padding: 2px 16px 0; border-left: 1px solid var(--brass-faint); border-top: none; }
.unit .step:first-child { border-left: none; }
.unit .step .sl { font-family: var(--mono); font-size: 9px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--muted); margin-bottom: 4px; }
.unit .step p { margin: 0; font-size: 12.5px; line-height: 1.6; color: var(--ink); }
.unit .tags { grid-column: 1 / -1; display: flex; flex-wrap: wrap; gap: 6px; padding: 10px 16px 0; }
.improve { grid-column: 1 / -1; margin: 12px 16px 0; padding: 9px 13px; border-left: 2px solid var(--brass); background: rgba(201,164,92,0.06); font-size: 12.5px; color: var(--ink-2); }
.improve b { color: var(--brass); font-weight: 500; font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.16em; text-transform: uppercase; }
@media (max-width: 880px) { .unit .flow { grid-template-columns: 1fr; gap: 10px; } .unit .step { border-left: none; border-top: 1px solid var(--brass-faint); padding: 10px 16px 0; } .unit .step:first-child { border-top: none; } }
.unit-toggle { font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.16em; text-transform: uppercase; background: none; border: 1px dashed var(--brass-line); color: var(--brass); padding: 6px 14px; cursor: pointer; margin-top: 10px; align-self: flex-start; transition: background .25s ease; }
.unit-toggle:hover { border-style: solid; background: rgba(201,164,92,0.08); }
.unit-toggle .arr { display: inline-block; transition: transform .45s cubic-bezier(.25,.8,.25,1); margin-left: 6px; }
.unit-toggle.open .arr { transform: rotate(180deg); }
.unit-fold { display: grid; grid-template-rows: 0fr; transition: grid-template-rows .6s cubic-bezier(.25,.8,.25,1); }
.unit-fold.open { grid-template-rows: 1fr; }
.unit-fold > .uf-inner { min-height: 0; overflow: hidden; }
@keyframes specIn { from { opacity: 0; transform: translateY(14px); } to { opacity: 1; transform: none; } }
.spec-in { animation: specIn .45s cubic-bezier(.2,.7,.2,1) both; }
#sp-more, #sp-less { background: none; color: var(--brass); border: 1px solid var(--brass-line); padding: 10px 32px; font-family: var(--mono); font-size: 10.5px; letter-spacing: 0.2em; text-transform: uppercase; cursor: pointer; }
#sp-more:hover, #sp-less:hover { background: rgba(201,164,92,0.08); }
@media (prefers-reduced-motion: reduce) { .unit-fold, .unit-toggle .arr { transition: none !important; } .spec-in { animation: none !important; } }
</style>"""

    html = f"""{BEGIN}
{css}

<div class="no" id="s10">10</div>
<h2>Instrument checks — reading the reader</h2>
<p>Everything above describes how the data was made; this section asks how far the machine reading can be trusted. Two checks, both computed from the shipped unit databases. They are also shown in the atlas, but they belong here: they are statements about the instrument, not findings about reviewers.</p>

<h3>Support status — where the instrument speaks with its own voice</h3>
<p>Every unit carries a <code>support_status</code> field assigned at structuring time: <b>reviewer_explicit</b> (grounded in the reviewer's stated words), <b>memo_inferred</b> (articulated by the DeepSeek memo from context rather than quoted), or <b>mixed</b>. The two tracks differ sharply by construction — the review-level 2026 track runs 19.8% explicit / 77.1% inferred / 3.1% mixed, while the forum-level track runs 57.4% / 40.8% / 1.7% — because the Layered prompts ask the memo to synthesize, and the Direct prompts demand line-ID citations. The share is not uniform across categories or years:</p>
<div class="fig-cap">Memo-inferred share, object × year — forum-level track (deeper violet = more inferred)</div>
<div class="hm-wrap"><div class="hm" id="mx-rel"></div></div>
<p class="hm-note">Categories and years where the violet deepens are where downstream figures speak more with the instrument's voice than the reviewer's. Rebuild: <code>uv run python scripts/build_panel_data.py</code> → <code>panel-data.json</code> (key <code>reliability</code>).</p>

<h3>Construct validity — do the induced categories track the venue's own decomposition?</h3>
<p>The taxonomy was induced from embeddings, not designed, so it needs an external criterion. ICLR asks reviewers for three sub-scores (soundness · presentation · contribution, 1–4; the fields exist only since 2024). For each object of scrutiny we compare mean sub-scores of reviews that carry at least one negative unit on that object against reviews at the <em>same overall rating</em> without one, weight the per-rating deltas by prevalence (cells with fewer than 30 reviews on either side are dropped), and read whether each criticism dents the sub-score it should. Computed over all 74,380 rated 2026 reviews.</p>
<div class="fig-cap">Rating-adjusted Δ sub-score when a negative unit is present (oxblood = drops, verdigris = rises)</div>
<div class="hm-wrap"><div class="hm" id="mx-con"></div></div>
<p class="hm-note">The grid largely agrees with the venue's own decomposition — clarity criticism dents <em>presentation</em> specifically (−0.35), novelty dents <em>contribution</em> (−0.12) — with one telling leak: theory criticism dents presentation more than soundness, as if "I could not follow the theory" were filed under presentation. Rebuild: <code>uv run python scripts/build_construct_data.py</code> → <code>construct-data.json</code>.</p>

<script>
const MX = {data_js};
(function () {{
  const fmt = n => n.toLocaleString("en-US");
  const pct = x => (100 * x).toFixed(1) + "%";
  const VAL_ORDER = ["negative", "uncertain", "mixed", "conditional", "positive"];
  const VAL_COLOR = {{ negative: "#e66767", uncertain: "#9085e9", mixed: "#d55181", conditional: "#c98500", positive: "#199e70" }};
  const objLabel = MX.objLabel, reaLabel = MX.reaLabel, objOrder = MX.objOrder, reaOrder = MX.reaOrder;

  // ---- reliability heatmap ----
  const R = MX.rel;
  const rel = document.getElementById("mx-rel");
  rel.style.gridTemplateColumns = `minmax(86px, 210px) repeat(${{R.years.length}}, 1fr)`;
  rel.insertAdjacentHTML("beforeend", `<div></div>` + R.years.map(y => `<div class="cl">'${{String(y).slice(2)}}</div>`).join(""));
  for (const o of objOrder) {{
    const vals = R.memo_inferred_share[o]; if (!vals) continue;
    rel.insertAdjacentHTML("beforeend", `<div class="rl">${{objLabel[o]}}</div>`);
    vals.forEach((v, i) => {{
      const cell = document.createElement("div");
      cell.className = "cell";
      cell.style.background = `color-mix(in oklab, #9085e9 ${{Math.round(v * 130)}}%, #161324)`;
      cell.title = `${{objLabel[o]}} · ${{R.years[i]}}: ${{pct(v)}} memo-inferred`;
      rel.appendChild(cell);
    }});
  }}

  // ---- construct-validity heatmap ----
  const SUBS = ["soundness", "presentation", "contribution"];
  const con = document.getElementById("mx-con");
  con.style.gridTemplateColumns = `minmax(86px, 210px) repeat(${{SUBS.length}}, 1fr)`;
  con.insertAdjacentHTML("beforeend", `<div></div>` + SUBS.map(x => `<div class="cl">${{x}}</div>`).join(""));
  for (const o of objOrder) {{
    con.insertAdjacentHTML("beforeend", `<div class="rl">${{objLabel[o]}}</div>`);
    for (const sub of SUBS) {{
      const v = (MX.construct[o] || {{}})[sub] || 0;
      const mag = Math.min(92, Math.round(Math.abs(v) / 0.35 * 100));
      const cell = document.createElement("div");
      cell.className = "cell";
      cell.style.background = `color-mix(in oklab, ${{v < 0 ? "#b45036" : "#2fa383"}} ${{mag}}%, #161324)`;
      cell.title = `negative ${{objLabel[o]}} unit × ${{sub}}: Δ mean = ${{v > 0 ? "+" : ""}}${{v.toFixed(3)}} (rating-adjusted)`;
      con.appendChild(cell);
    }}
  }}

}})();
</script>
{END}
"""
    # the ▾ escape must survive into JS source
    html = html.replace("\\\\u25be", "\\u25be")

    s = METHOD.read_text()
    if BEGIN in s and END in s:
        s = s[: s.index(BEGIN)] + html + s[s.index(END) + len(END) + 1 :]
    else:
        assert "<footer>" in s
        s = s.replace("<footer>", html + "\n<footer>", 1)

    # TOC entries
    s = s.replace('  <a href="#s11"><span class="tno">11</span>Raw specimens — the reading, inspectable</a>\n', '', 1)
    if "#s10" not in s:
        s = s.replace(
            '  <a href="#s9"><span class="tno">09</span>Cost ledger</a>\n</div>',
            '  <a href="#s9"><span class="tno">09</span>Cost ledger</a>\n'
            '  <a href="#s10"><span class="tno">10</span>Instrument checks — reading the reader</a>\n</div>',
            1,
        )
    # footer scope line
    s = s.replace("<span>Scope: data creation only</span>", "<span>Scope: data creation &amp; instrument validation</span>", 1)

    METHOD.write_text(s)
    print(f"method extras injected ({len(html) / 1e6:.2f} MB block); method.html now {len(s) / 1e6:.2f} MB")


if __name__ == "__main__":
    main()
